AWS SQS support added
BrandEmbassy/queue-management pull request #39
Opened 2022-03-30 09:05 UTC by adambezecny

This PR adds classed needed to connect to AWS SQS messaging. These are analogy/counterparts to respective RabbitMQ classes. This will enable to use queue-management library by client app with transparent switch from RabbitMQ to SQS in the future.

2022-04-04 17:04 UTC, milan-zelenka reviewed
Partial review

2022-04-04 17:04 UTC, milan-zelenka commented on src/Queue/AWSSQS/SqsMessageFactory.php
> +        return $sqsMessages;
```suggestion
        return array_map(
        fn($message) => return new SqsMessage($message, $queueUrl),
        $awsResultMessages
        );
```
Might not be the exact code, but my point is it could be easier than using foreach

2022-04-05 09:11 UTC, adambezecny commented on src/Queue/AWSSQS/SqsMessage.php
> +    public const ATTR_MESSAGEBODY = 'MessageBody'; // for sending only. when receiving message actual attr name is 'Body'
fixed. **SqsMessageFields** class added.

2022-04-05 09:13 UTC, adambezecny commented on src/Queue/Common/LoggerHelper.php
> +            'previousException' => $exception->getPrevious(),
I would be careful here. This is the original code, just externalized into _LoggerHelper_ so that we can reuse in SQS related functionality. I would prefer not to change it since it probably works

2022-04-05 09:35 UTC, adambezecny commented on src/Queue/Common/LoggerHelper.php
> +    public static function logDelayableProcessFailException(DelayableProcessFailExceptionInterface $exception, LoggerInterface $logger): void
nice one! I did fix it

2022-04-05 09:37 UTC, adambezecny commented on src/Redis/RedisClient.php
> +class RedisClient
I think this is good idea but definitely should be addressed as separate initiative. Right now this would mean lot of effort before we could continue with queue-management. So I would probably put it on backlog as improvement/deduplication.

2022-04-05 09:56 UTC, adambezecny commented on src/Queue/AWSSQS/MessageDeduplicationDefault.php
> + * @final
coding standards are up to date. added final where appropriate, if you spot more, let me know concrete places where should be added.

2022-04-05 10:01 UTC, adambezecny commented on src/Queue/AWSSQS/SqsConsumer.php
> +                'ReceiptHandle' => $message->getReceiptHandle(),
fixed

2022-04-05 10:19 UTC, adambezecny commented on src/Queue/AWSSQS/SqsConsumer.php
> +                ['exception' => $exception],
refactored, see https://github.com/BrandEmbassy/queue-management/commit/065ef2507077cf05845caf98102bc3b0d2f7eb5e

2022-04-05 10:21 UTC, adambezecny commented on src/Queue/AWSSQS/SqsConsumer.php
> +                'Consumer failed, job requeued: ' . $exception->getMessage(),
do we want to really change this? again this is original code, I prefer not to touch it unless it really causes some troubles. we might introduce some bug by it.

2022-04-05 10:34 UTC, adambezecny commented on src/Queue/AWSSQS/SqsMessageFactory.php
> +        /**
assertion added

2022-04-05 10:35 UTC, adambezecny commented on src/Queue/AWSSQS/SqsMessageFactory.php
> +        return $sqsMessages;
I am not happy with this proposed change. **_foreach_** is very easy to read, **_array_map_** with callback function is on the contrary difficult to read.  What exactly this change will improve? I think there is no benefit and readability will suffer.

2022-04-05 10:43 UTC, adambezecny commented on src/Queue/AWSSQS/MessageDeduplicationInterface.php
> +interface MessageDeduplicationInterface
refactored

2022-04-05 10:46 UTC, adambezecny commented on src/Queue/AWSSQS/SqsClientException.php
> +    }
this is consistent with design of **_BE\QueueManagement\Queue\RabbitMQ\ConnectionException_**.

The overall change is already quite big, I would like to prevent situation when we will be doing too many improvements into existing code as it might destabilize the service and introduce some new bugs/undesired side effects. If this is really necessary to do I would suggest to address it separately (in next iteration for example).

2022-04-05 10:48 UTC, adambezecny commented on src/Queue/AWSSQS/SqsClientException.php
> +            sprintf('Invalid DelaySeconds specifie: (%d). Value must be integer from 0 to 900 seconds.', $delay),
typo fixed

2022-04-05 10:52 UTC, adambezecny commented on src/Queue/AWSSQS/MessageDeduplicationDefault.php
> +        int $deduplicationWindowSizeSec = 300
You can pass them even now, see sample app in **_sqs_** branch: https://github.com/BrandEmbassy/queue-management/blob/sqs/examples/sample-app/config-sqs.neon#L50

not super elegant but works. Do we still need to refactor it?

2022-04-05 11:03 UTC, adambezecny commented on src/Queue/AWSSQS/MessageDeduplicationDefault.php
> +        $mutex = $this->mutex;
fixed

2022-04-05 11:03 UTC, adambezecny commented on src/Queue/AWSSQS/MessageDeduplicationDefault.php
> +        $deduplicationWindowSizeSec = $this->deduplicationWindowSizeSec;
i like the short names and too much $this->xx looks ugly :)  but I fixed it

2022-04-05 11:04 UTC, adambezecny commented on src/Queue/AWSSQS/MessageDeduplicationDefault.php
> +            $alreadySeen = $mutex->synchronized(function () use ($messageId, $redisClient, $queueName, $deduplicationWindowSizeSec): bool {
fixed

2022-04-05 11:04 UTC, adambezecny commented on src/Queue/AWSSQS/MessageDeduplicationDefault.php
> +            $alreadySeen = $mutex->synchronized(function () use ($messageId, $redisClient, $queueName, $deduplicationWindowSizeSec): bool {
fixed, only $message is now in use statement, since it seems function param needs to be consumed by closure explicitly

2022-04-05 11:08 UTC, adambezecny commented on src/Queue/AWSSQS/MessageDeduplicationDefault.php
> +        } catch (LockReleaseException $unlockException) {
fixed

2022-04-05 11:08 UTC, adambezecny commented on src/Queue/AWSSQS/MessageDeduplicationDefault.php
> +        int $deduplicationWindowSizeSec = 300
fixed

2022-04-05 11:15 UTC, adambezecny commented on src/Queue/AWSSQS/MessageDeduplicationDefault.php
> +                    $redisClient->setWithTtl($rk, '1', $deduplicationWindowSizeSec);
currently in case of redis error exception will be thrown causing job processing to fail (and hence respectivef message will be re-consumed). Treating the redis error ecplicitly within **_isDuplicate_** method probably means we need to assume message is not duplicate and allow its processing. Is this what we want? I would prefer to propagate redis error in this case.

2022-04-05 11:16 UTC, adambezecny commented on src/Queue/AWSSQS/MessageDeduplicationDefault.php
> +                    $redisClient->setWithTtl($rk, '1', $deduplicationWindowSizeSec);
also depends how these errors are common. maybe we would be handling here something which is occurring only rarely.

2022-04-05 11:20 UTC, adambezecny commented on src/Queue/AWSSQS/MessageDeduplicationDefault.php
> +            }
fixed. if/else redesigned to early exit pattern

2022-04-05 11:41 UTC, adambezecny commented on src/Queue/AWSSQS/MessageDeduplicationDefault.php
> +                return $codeResult;
it is:) this handles the situation when mutex closure has successfully finished (always returning boolean) but during lock releasing something went wrong. This pattern is taken directly from official documentation, see https://github.com/php-lock/lock 

so if **_codeResult_** will be not null it will always be **_boolean_**. this is safe

2022-04-05 11:42 UTC, adambezecny commented on src/Queue/AWSSQS/MessageDeduplicationDefault.php
> +            $this->logger->warning('Error when releasing lock ' . $errorMessage);
again see link attached above. this is exactly how library should be used. I think this is OK.

2022-04-05 11:45 UTC, adambezecny commented on src/Queue/AWSSQS/MessageDeduplicationDefault.php
> +            $errorMessage = $unlockException->getCodeException() !== null ? $unlockException->getCodeException()->getMessage() : '';
fixed. I changed it to **_not available_**

2022-04-05 11:49 UTC, adambezecny commented on src/Queue/AWSSQS/SqsClientFactory.php
> +    public function __construct(array $connectionConfig)
sorry not sure how exactly you mean it. Can you provide some code example(s)? But again: this is strictly consistent with what we have for Rabbit today, see **_BE\QueueManagement\Queue\RabbitMQ\ConnectionFactory_**

The purpose of this PR is not to redesign and improve as much as possible but rather build SQS support as analogy to what we have today for Rabbit. Because of that I am not very happy to divert from original design of **ConnectionFactory**.

2022-04-05 11:52 UTC, adambezecny commented on src/Queue/AWSSQS/SqsConsumer.php
> +        try {
again keeping consistent with RabbitMQConsumer which handles here 2 basic scenarios:

- ConsumerFailedExceptionInterface -> message will be requeued
- UnresolvableProcessFailExceptionInterface -> message will be removed

to make switch from Rabbit to SQS transparent for consuming application this logic must be identical.

2022-04-05 12:02 UTC, adambezecny commented on src/Queue/AWSSQS/SqsConsumer.php
> +                return;
fair point. refactored into **deleteSqsMessage**

2022-04-07 13:20 UTC, damianbrhel commented on src/Queue/AWSSQS/MessageDeduplicationDefault.php
> +    private const DEDUPLICATION_KEY_PREFIX = 'AWS_DEDUP_PREFIX_';
what is it good for? "AWS_DEDUP_PREFIX_" seems to be more needed to be dynamic

2022-04-20 07:47 UTC, adambezecny commented on src/Queue/AWSSQS/MessageDeduplicationDefault.php
> +    private const DEDUPLICATION_KEY_PREFIX = 'AWS_DEDUP_PREFIX_';
this is **default** key prefix for redis keys that are intended for message deduplication. The whole point is that this is default implementation that can be customized, so real integrations will provide prefix as needed. making this configurable will not bring much value.

2022-04-21 18:29 UTC, adambezecny commented on src/Queue/AWSSQS/SqsClientFactory.php
> +    public function __construct(array $connectionConfig)
SqsClientFactory was remove, underlying method is now part of SqsQueueManager since it needs to access AWS S3 client in case of big messages. Hence this comment can be closed/resolved.

2022-05-11 14:00 UTC, milan-zelenka commented on src/Queue/AWSSQS/SqsQueueManager.php
> +                if (count($messages) > 0) {
I've encountered this situation while testing:
````
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in
/var/www/html/vendor/brandembassy/queue-management/src/Queue/AWSSQS/SqsQueueManager.php on line 145
```

2022-06-07 13:13 UTC, PetrHeinz requested changes
Due to the complexity of the PR, I wasn't able to concentrate long enought to properly review all parts. I have yet to:

- review AWS SQS docs
- compare SQS solution to the RabbitMQ
- fully review critical parts of the SQS solution
- verify there are no important missing tests

In the future, I would recommend making necessary refactoring first in a separate PR (eg. extraction of LoggerHelper), implementing simplest end-to-end solution (eg. without deduplication and S3 handling) and the adding the missing parts in separate PRs.

I feel like I've missed a lot during the review.

2022-06-27 09:56 UTC, PetrHeinz commented
This needs to be released as a MAJOR version due to the BC break in JobDefinition. I would suggest to release as a beta so we can make further BC breaks during the SQS tweaking.

2022-06-28 11:59 UTC, lukasHod commented on src/Queue/AWSSQS/SqsQueueManager.php
> +        $sqsMessage = [
renamed to $messageToSend

2022-06-28 12:13 UTC, lukasHod commented on src/Queue/AWSSQS/SqsMessageFields.php
> +    public const MESSAGEATTRIBUTES = 'MessageAttributes'; // for sending only. for reading use ATTRIBUTES
sending fields moved to SqsSendingMessageFields but for the our created SqsMessage I left the SqsMessageFields

2022-06-28 12:16 UTC, lukasHod commented on src/Queue/AWSSQS/AwsClientFactory.php
> +        ];
its used only in AwsClientFactory so I changed it to private

2022-06-28 14:16 UTC, lukasHod commented on src/Queue/AWSSQS/SqsQueueManager.php
> +    public function fromAwsResultMessages(array $awsResultMessages, string $queueUrl): array
I just make it private. It would be nice a tleast move it into some factory but there is some reconnection logic to s3 and sqs and s3 upload logic in this class so it would require quite a refactor

2022-06-28 14:34 UTC, lukasHod commented on src/Logging/LoggerHelper.php
> +            LoggerContextField::PREVIOUS_EXCEPTION => $exception->getPrevious(),
I would leave it as it is for now. There will be changes in monitoring of sqs processing so it may change in near future

2022-06-29 08:48 UTC, PetrHeinz approved these changes

2022-06-29 11:52 UTC, TomasHodan01 approved these changes

2022-06-30 08:53 UTC, merged