DE-35424 Add TimeOfExecution to the JobInterface
BrandEmbassy/queue-management pull request #56
Opened 2022-09-12 09:50 UTC by jakubkulhanek

2022-09-13 11:15 UTC, dominikvoda commented on src/Jobs/JobInterface.php
> +    public function setTimeOfExecution(?int $timeOfExecution): void;  // $timeOfExecution = Timestamp of execution time
name the method in a way we don't need extra comment

2022-09-13 11:15 UTC, dominikvoda requested changes
missing tests

2022-09-13 12:33 UTC, PetrHeinz requested changes
PR description is missing. This PR just adds a new attribute and it's not really clear how it's planned to be used...

If this work is done here in the library, it should be really intuitive to use. Maybe we can implement this feature in our code instead, if that's too hard to achieve?

Also, this will create a BC break (as you're adding new methods to an existing interface), it should be clearly marked as such.

2022-09-13 12:33 UTC, PetrHeinz commented on src/Jobs/JobInterface.php
> +    public function setTimeOfExecution(?int $timeOfExecution): void;
Why `int` and not `DateTimeImmutable`?

Maybe it would deserve a better naming. How about `getExecutionPlannedAt(): ?DateTimeImmutable` and `executionPlanned(?DateTimeImmutable $plannedAt)`, to be a bit more concise with `getExecutionStartedAt` / `executionStarted`.

2022-09-13 12:33 UTC, PetrHeinz commented on src/Queue/AWSSQS/SqsQueueManager.php
>              self::DELAY_SECONDS => $delayInSeconds,
Here you still delay it by `$delayInSeconds` and not use the new attribute. Maybe you should add a `TODO` if you're planning to add it in a new PR...

2022-09-13 12:33 UTC, PetrHeinz commented on src/Jobs/FailResolving/PushDelayedResolver.php
> +        $job->setTimeOfExecution(null);
This seems a bit unintuitive. Why do we set that to NULL during resolving? Maybe we should name it better or unify it with `incrementAttempts`...

2022-09-13 12:33 UTC, PetrHeinz commented on src/Jobs/JobInterface.php
> +    public function getTimeOfExecution(): ?int;
This value is not used anywhere (except as a hasser). Maybe a TODO is missing?

2022-09-13 12:33 UTC, PetrHeinz commented on src/Queue/AWSSQS/SqsQueueManager.php
> +            $job->setTimeOfExecution($job->getCreatedAt()->getTimestamp() + $delayInSeconds);
Why is this set only in the SQS queue manager? In RabbitMQ, all job will have execution time of NULL?

2022-09-13 12:34 UTC, jakubkulhanek commented on src/Jobs/JobInterface.php
> +    public function setTimeOfExecution(?int $timeOfExecution): void;
I took this name from platform. For me it is better to use simillary naming

2022-09-13 12:35 UTC, jakubkulhanek commented on src/Queue/AWSSQS/SqsQueueManager.php
>              self::DELAY_SECONDS => $delayInSeconds,
I do not understand what you mean

2022-09-13 12:37 UTC, jakubkulhanek commented on src/Queue/AWSSQS/SqsQueueManager.php
> +            $job->setTimeOfExecution($job->getCreatedAt()->getTimestamp() + $delayInSeconds);
Because this delaying must work only for SQS

2022-09-13 12:38 UTC, jakubkulhanek commented on src/Jobs/JobInterface.php
> +    public function getTimeOfExecution(): ?int;
?

2022-09-13 12:38 UTC, jakubkulhanek commented on src/Jobs/FailResolving/PushDelayedResolver.php
> +        $job->setTimeOfExecution(null);
?

2022-09-14 10:07 UTC, PetrHeinz approved these changes
PR description is still missing.

2022-09-14 10:07 UTC, PetrHeinz commented on tests/Queue/AWSSQS/SqsConsumerTest.php
> +        $exampleJob->setExecutionPlannedAt(new DateTimeImmutable('2016-08-15T17:00:00+00:00'));
[o] It would be nice to have at least two different data sets, one in the future (just like you have) and one in immediate future (`2016-08-15T15:00:01+00:00`) to test the edge case. Ideally, you should also test time zones.

2022-09-14 10:07 UTC, PetrHeinz commented on tests/Queue/AWSSQS/SqsConsumerTest.php
> +        $exampleJob->setExecutionPlannedAt(new DateTimeImmutable('2016-08-15T14:00:00+00:00'));
[o] It would be nice to have at least two different data sets, one in the past (just like you have) and one in the present (`2016-08-15T15:00:00+00:00`) to test the edge case. Ideally, you should also test time zones.

2022-09-14 10:26 UTC, PetrHeinz commented on src/Queue/AWSSQS/SqsQueueManager.php
> +                'Requested delays is greater than SQS limit. Job execution has been planned and will be requeued until then.',
type (probably mine :grin:)
```suggestion
                'Requested delay is greater than SQS limit. Job execution has been planned and will be requeued until then.',
```

2022-09-14 11:24 UTC, PetrHeinz commented on src/Queue/AWSSQS/SqsQueueManager.php
> +                'Requested delas is greater than SQS limit. Job execution has been planned and will be requeued until then.',
You deleted the wrong letter :rofl: 
```suggestion
                'Requested delay is greater than SQS limit. Job execution has been planned and will be requeued until then.',
```

2022-09-14 11:26 UTC, PetrHeinz commented on tests/Jobs/Execution/JobLoaderTest.php
> +        }
`Assert::assertEquals()` tady nefunguje?

2022-09-14 11:30 UTC, PetrHeinz commented on tests/Queue/AWSSQS/SqsQueueManagerTest.php
> +        $this->loggerMock->hasInfo('Requested delay is greater than SQS limit. Job execution has been planned and will be requeued until then.');
Tohle není assert, jen zavoláš hasser, který ti vrátí FALSE (zrovna teď, protože je v implementaci typo s `delas`).

2022-09-14 11:50 UTC, lukasHod commented on src/Jobs/HasExecutionPlannedAt.php
> +trait HasExecutionPlannedAt
what is the reason having this trait? We can just extend SimpleJob with those methods. Is there any plan to use it somewhere else?

2022-09-14 11:57 UTC, jakubkulhanek commented on src/Jobs/HasExecutionPlannedAt.php
> +trait HasExecutionPlannedAt
It is for easier work in jobs which are using the JobInterface.
It is good to have one implementation in trait instead of write same code in different jobs

2022-09-14 12:07 UTC, lukasHod approved these changes

2022-09-16 11:49 UTC, merged